### ISSUE TITLE
Issue introduced in package version >=1.56.1 with protofbuf <= 3.18.1

### ISSUE THREAD

**Issue by DManowitz** [googleapis/python-api-common-protos#121]
I get the following error when I have googleapis-common-protos version >= 1.56.1 installed along with protobuf package version <= 3.18.1:

>>> from google.rpc import error_details_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\manow\miniconda3\envs\py37_gAPIs_test\lib\site-packages\google\rpc\error_details_pb2.py", line 39, in <module>
    _RETRYINFO = DESCRIPTOR.message_types_by_name["RetryInfo"]
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

I'm using Windows 10, and I've reproduced the problem with python 3.7 and 3.8.

**Comment by vam-google** [comment]
Those files have been regenerated under assumption that they are compatible with protobuf 3.15.x (https://github.com/googleapis/python-api-common-protos/pull/95) but given the time when it was done and the available tools at that moment, most likely it got regenerated with protobuf 3.19.x. @parthea Can you please verify it? In any case, I would guess we need to update dependencies (https://github.com/googleapis/python-api-common-protos/blob/main/setup.py#L25) to be `>= protobuf 3.19.*`.

**Comment by parthea** [comment]
Closing due to no activity. Please open a new issue if there is still a problem.
