### ISSUE TITLE
1.53.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [googleapis/python-api-common-protos#71]
#### Environment details
  - OS type and version: Linix/x86_64
  - Python version: `Python 3.8.12`
  - pip version: `pip 21.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)`
  - googleapis-common-protos `1.53.0`

#### Steps to reproduce
- "setup.py build"
- "setup.py install --root </install/prefix>"
- run nox with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Output of the nox command:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-googleapis-common-protos-1.53.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ nox
nox > Running session blacken
nox > Session blacken skipped: Python interpreter 3.6 not found.
nox > Running session lint_setup_py
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/lint_setup_py
nox > Command /usr/bin/python3 -m virtualenv /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.53.0/.nox/lint_setup_py -p python3.8 failed with exit code 1:
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'

nox > Session lint_setup_py failed.
nox > Running session test-3.6(pubsub)
nox > Session test-3.6(pubsub) skipped: Python interpreter 3.6 not found.
nox > Running session test-3.6(texttospeech)
nox > Session test-3.6(texttospeech) skipped: Python interpreter 3.6 not found.
nox > Running session test-3.6(speech)
nox > Session test-3.6(speech) skipped: Python interpreter 3.6 not found.
nox > Running session test-3.7(pubsub)
nox > Session test-3.7(pubsub) skipped: Python interpreter 3.7 not found.
nox > Running session test-3.7(texttospeech)
nox > Session test-3.7(texttospeech) skipped: Python interpreter 3.7 not found.
nox > Running session test-3.7(speech)
nox > Session test-3.7(speech) skipped: Python interpreter 3.7 not found.
nox > Running session test-3.8(pubsub)
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/test-3-8-pubsub
nox > Command /usr/bin/python3 -m virtualenv /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.53.0/.nox/test-3-8-pubsub -p python3.8 failed with exit code 1:
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'

nox > Session test-3.8(pubsub) failed.
nox > Running session test-3.8(texttospeech)
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/test-3-8-texttospeech
nox > Command /usr/bin/python3 -m virtualenv /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.53.0/.nox/test-3-8-texttospeech -p python3.8 failed with exit code 1:
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'

nox > Session test-3.8(texttospeech) failed.
nox > Running session test-3.8(speech)
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/test-3-8-speech
nox > Command /usr/bin/python3 -m virtualenv /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.53.0/.nox/test-3-8-speech -p python3.8 failed with exit code 1:
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'

nox > Session test-3.8(speech) failed.
nox > Running session test-3.9(pubsub)
nox > Session test-3.9(pubsub) skipped: Python interpreter 3.9 not found.
nox > Running session test-3.9(texttospeech)
nox > Session test-3.9(texttospeech) skipped: Python interpreter 3.9 not found.
nox > Running session test-3.9(speech)
nox > Session test-3.9(speech) skipped: Python interpreter 3.9 not found.
nox > Running session generate_protos
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/generate_protos
nox > Command /usr/bin/python3 -m virtualenv /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.53.0/.nox/generate_protos -p python3.8 failed with exit code 1:
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'

nox > Session generate_protos failed.
nox > Ran multiple sessions:
nox > * blacken: skipped
nox > * lint_setup_py: failed
nox > * test-3.6(pubsub): skipped
nox > * test-3.6(texttospeech): skipped
nox > * test-3.6(speech): skipped
nox > * test-3.7(pubsub): skipped
nox > * test-3.7(texttospeech): skipped
nox > * test-3.7(speech): skipped
nox > * test-3.8(pubsub): failed
nox > * test-3.8(texttospeech): failed
nox > * test-3.8(speech): failed
nox > * test-3.9(pubsub): skipped
nox > * test-3.9(texttospeech): skipped
nox > * test-3.9(speech): skipped
nox > * generate_protos: failed
```

**Comment by kloczek** [comment]
Just tested 1.56.2 and still nox is not workinng.
As I'm trying to standarise all my packages with pytjon modules to use pytest I would be more interested usimf pytest.
Currently pytest is failing as well.
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-googleapis-common-protos-1.56.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-googleapis-common-protos-1.56.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-api-common-protos-1.56.2
collected 1 item

tests/unit/test_google_api_error_reason.py F                                                                                                                         [100%]

================================================================================= FAILURES =================================================================================
____________________________________________________________________________ test_error_reason _____________________________________________________________________________

    def test_error_reason():
>       from google.api import error_reason_pb2

tests/unit/test_google_api_error_reason.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    """Generated protocol buffer code."""
>   from google.protobuf.internal import enum_type_wrapper
E   ModuleNotFoundError: No module named 'google.protobuf'

../../BUILDROOT/python-googleapis-common-protos-1.56.2-2.fc35.x86_64/usr/lib/python3.8/site-packages/google/api/error_reason_pb2.py:20: ModuleNotFoundError
========================================================================= short test summary info ==========================================================================
FAILED tests/unit/test_google_api_error_reason.py::test_error_reason - ModuleNotFoundError: No module named 'google.protobuf'
============================================================================ 1 failed in 0.06s =============================================================================
```
</details>

**Comment by parthea** [comment]
Closing due to no activity. Please open a new issue if this is still a problem.
